# Generated by Django 5.1.4 on 2024-12-08 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_size_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
