# Generated by Django 5.1.4 on 2025-01-31 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_users_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='users_like',
        ),
    ]
